USE inventory;

create table ADRC
(
    CLIENT             CHAR(3)     not null,
    ADDRNUMBER         VARCHAR(10) not null,
    DATE_FROM          DATE        not null,
    NATION             VARCHAR(1)  not null,
    DATE_TO            DATE,
    TITLE              VARCHAR(4),
    NAME1              VARCHAR(40),
    NAME2              VARCHAR(40),
    NAME3              VARCHAR(40),
    NAME4              VARCHAR(40),
    NAME_TEXT          VARCHAR(50),
    NAME_CO            VARCHAR(40),
    CITY1              VARCHAR(40),
    CITY2              VARCHAR(40),
    CITY_CODE          VARCHAR(12),
    CITYP_CODE         VARCHAR(8),
    HOME_CITY          VARCHAR(40),
    CITYH_CODE         VARCHAR(12),
    CHCKSTATUS         VARCHAR(1),
    REGIOGROUP         VARCHAR(8),
    POST_CODE1         VARCHAR(10),
    POST_CODE2         VARCHAR(10),
    POST_CODE3         VARCHAR(10),
    PCODE1_EXT         VARCHAR(10),
    PCODE2_EXT         VARCHAR(10),
    PCODE3_EXT         VARCHAR(10),
    PO_BOX             VARCHAR(10),
    DONT_USE_P         VARCHAR(4),
    PO_BOX_NUM         VARCHAR(1),
    PO_BOX_LOC         VARCHAR(40),
    CITY_CODE2         VARCHAR(12),
    PO_BOX_REG         VARCHAR(3),
    PO_BOX_CTY         VARCHAR(3),
    POSTALAREA         VARCHAR(15),
    TRANSPZONE         VARCHAR(10),
    STREET             VARCHAR(60),
    DONT_USE_S         VARCHAR(4),
    STREETCODE         VARCHAR(12),
    STREETABBR         VARCHAR(2),
    HOUSE_NUM1         VARCHAR(10),
    HOUSE_NUM2         VARCHAR(10),
    HOUSE_NUM3         VARCHAR(10),
    STR_SUPPL1         VARCHAR(40),
    STR_SUPPL2         VARCHAR(40),
    STR_SUPPL3         VARCHAR(40),
    LOCATION           VARCHAR(40),
    BUILDING           VARCHAR(20),
    FLOOR              VARCHAR(10),
    ROOMNUMBER         VARCHAR(10),
    COUNTRY            VARCHAR(3),
    LANGU              CHAR(1),
    REGION             VARCHAR(3),
    ADDR_GROUP         VARCHAR(4),
    FLAGGROUPS         VARCHAR(1),
    PERS_ADDR          VARCHAR(1),
    SORT1              VARCHAR(20),
    SORT2              VARCHAR(20),
    SORT_PHN           VARCHAR(20),
    DEFLT_COMM         VARCHAR(3),
    TEL_NUMBER         VARCHAR(30),
    TEL_EXTENS         VARCHAR(10),
    FAX_NUMBER         VARCHAR(30),
    FAX_EXTENS         VARCHAR(10),
    FLAGCOMM2          VARCHAR(1),
    FLAGCOMM3          VARCHAR(1),
    FLAGCOMM4          VARCHAR(1),
    FLAGCOMM5          VARCHAR(1),
    FLAGCOMM6          VARCHAR(1),
    FLAGCOMM7          VARCHAR(1),
    FLAGCOMM8          VARCHAR(1),
    FLAGCOMM9          VARCHAR(1),
    FLAGCOMM10         VARCHAR(1),
    FLAGCOMM11         VARCHAR(1),
    FLAGCOMM12         VARCHAR(1),
    FLAGCOMM13         VARCHAR(1),
    ADDRORIGIN         VARCHAR(4),
    MC_NAME1           VARCHAR(25),
    MC_CITY1           VARCHAR(25),
    MC_STREET          VARCHAR(25),
    EXTENSION1         VARCHAR(40),
    EXTENSION2         VARCHAR(40),
    TIME_ZONE          VARCHAR(6),
    TAXJURCODE         VARCHAR(15),
    ADDRESS_ID         VARCHAR(10),
    LANGU_CREA         CHAR(1),
    PO_BOX_LOBBY       VARCHAR(40),
    DELI_SERV_TYPE     VARCHAR(4),
    DELI_SERV_NUMBER   VARCHAR(10),
    ARCHIVE_FLAG$      CHAR(1),
    ARCHIVE_TIMESTAMP$ DATE,
    constraint ADRC_PK primary key (ADDRNUMBER, DATE_FROM, NATION, CLIENT)
) comment ='Addresses (Business Address Services)';

create table KNA1
(
    MANDT            CHAR(3)     not null,
    KUNNR            VARCHAR(10) not null,
    LAND1            VARCHAR(3),
    NAME1            VARCHAR(35),
    NAME2            VARCHAR(35),
    ORT01            VARCHAR(35),
    PSTLZ            VARCHAR(10),
    REGIO            VARCHAR(3),
    SORTL            VARCHAR(10),
    STRAS            VARCHAR(35),
    TELF1            VARCHAR(16),
    TELFX            VARCHAR(31),
    XCPDK            VARCHAR(1),
    ADRNR            VARCHAR(10),
    MCOD1            VARCHAR(25),
    MCOD2            VARCHAR(25),
    MCOD3            VARCHAR(25),
    ANRED            VARCHAR(15),
    AUFSD            VARCHAR(2),
    BAHNE            VARCHAR(25),
    BAHNS            VARCHAR(25),
    BBBNR            DECIMAL(7),
    BBSNR            INTEGER(5),
    BEGRU            VARCHAR(4),
    BRSCH            VARCHAR(4),
    BUBKZ            DECIMAL(1),
    DATLT            VARCHAR(14),
    ERDAT            DATE,
    ERNAM            VARCHAR(12),
    EXABL            VARCHAR(1),
    FAKSD            VARCHAR(2),
    FISKN            VARCHAR(10),
    KNAZK            VARCHAR(2),
    KNRZA            VARCHAR(10),
    KONZS            VARCHAR(10),
    KTOKD            VARCHAR(4),
    KUKLA            VARCHAR(2),
    LIFNR            VARCHAR(10),
    LIFSD            VARCHAR(2),
    LOCCO            VARCHAR(10),
    LOEVM            VARCHAR(1),
    NAME3            VARCHAR(35),
    NAME4            VARCHAR(35),
    NIELS            VARCHAR(2),
    ORT02            VARCHAR(35),
    PFACH            VARCHAR(10),
    PSTL2            VARCHAR(10),
    COUNC            VARCHAR(3),
    CITYC            VARCHAR(4),
    RPMKR            VARCHAR(5),
    SPERR            VARCHAR(1),
    SPRAS            CHAR(1),
    STCD1            VARCHAR(16),
    STCD2            VARCHAR(11),
    STKZA            VARCHAR(1),
    STKZU            VARCHAR(1),
    TELBX            VARCHAR(15),
    TELF2            VARCHAR(16),
    TELTX            VARCHAR(30),
    TELX1            VARCHAR(30),
    LZONE            VARCHAR(10),
    XZEMP            VARCHAR(1),
    VBUND            VARCHAR(6),
    STCEG            VARCHAR(20),
    DEAR1            VARCHAR(1),
    DEAR2            VARCHAR(1),
    DEAR3            VARCHAR(1),
    DEAR4            VARCHAR(1),
    DEAR5            VARCHAR(1),
    GFORM            VARCHAR(2),
    BRAN1            VARCHAR(10),
    BRAN2            VARCHAR(10),
    BRAN3            VARCHAR(10),
    BRAN4            VARCHAR(10),
    BRAN5            VARCHAR(10),
    EKONT            VARCHAR(10),
    UMSAT            DECIMAL(8, 2),
    UMJAH            DECIMAL(4),
    UWAER            CHAR(5),
    JMZAH            DECIMAL(6),
    JMJAH            DECIMAL(4),
    KATR1            VARCHAR(2),
    KATR2            VARCHAR(2),
    KATR3            VARCHAR(2),
    KATR4            VARCHAR(2),
    KATR5            VARCHAR(2),
    KATR6            VARCHAR(3),
    KATR7            VARCHAR(3),
    KATR8            VARCHAR(3),
    KATR9            VARCHAR(3),
    KATR10           VARCHAR(3),
    STKZN            VARCHAR(1),
    UMSA1            DECIMAL(15, 2),
    TXJCD            VARCHAR(15),
    PERIV            VARCHAR(2),
    ABRVW            VARCHAR(3),
    INSPBYDEBI       VARCHAR(1),
    INSPATDEBI       VARCHAR(1),
    KTOCD            VARCHAR(4),
    PFORT            VARCHAR(35),
    WERKS            VARCHAR(4),
    DTAMS            VARCHAR(1),
    DTAWS            VARCHAR(2),
    DUEFL            VARCHAR(1),
    HZUOR            DECIMAL(2),
    SPERZ            VARCHAR(1),
    ETIKG            VARCHAR(10),
    CIVVE            VARCHAR(1),
    MILVE            VARCHAR(1),
    KDKG1            VARCHAR(2),
    KDKG2            VARCHAR(2),
    KDKG3            VARCHAR(2),
    KDKG4            VARCHAR(2),
    KDKG5            VARCHAR(2),
    XKNZA            VARCHAR(1),
    FITYP            VARCHAR(2),
    STCDT            VARCHAR(2),
    STCD3            VARCHAR(18),
    STCD4            VARCHAR(18),
    XICMS            VARCHAR(1),
    XXIPI            VARCHAR(1),
    XSUBT            VARCHAR(3),
    CFOPC            VARCHAR(2),
    TXLW1            VARCHAR(3),
    TXLW2            VARCHAR(3),
    CCC01            VARCHAR(1),
    CCC02            VARCHAR(1),
    CCC03            VARCHAR(1),
    CCC04            VARCHAR(1),
    CASSD            VARCHAR(2),
    KNURL            VARCHAR(132),
    J_1KFREPRE       VARCHAR(10),
    J_1KFTBUS        VARCHAR(30),
    J_1KFTIND        VARCHAR(30),
    CONFS            VARCHAR(1),
    UPDAT            DATE,
    UPTIM            DATE,
    NODEL            VARCHAR(1),
    DEAR6            VARCHAR(1),
    ALC              VARCHAR(8),
    PMT_OFFICE       VARCHAR(5),
    PSOFG            VARCHAR(10),
    PSOIS            VARCHAR(20),
    PSON1            VARCHAR(35),
    PSON2            VARCHAR(35),
    PSON3            VARCHAR(35),
    PSOVN            VARCHAR(35),
    PSOTL            VARCHAR(20),
    PSOHS            VARCHAR(6),
    PSOST            VARCHAR(28),
    PSOO1            VARCHAR(50),
    PSOO2            VARCHAR(50),
    PSOO3            VARCHAR(50),
    PSOO4            VARCHAR(50),
    PSOO5            VARCHAR(50),
    _VSO_R_PALHGT    DECIMAL(13, 3),
    _VSO_R_PAL_UL    CHAR(3),
    _VSO_R_PK_MAT    VARCHAR(1),
    _VSO_R_MATPAL    VARCHAR(18),
    _VSO_R_I_NO_LYR  DECIMAL(2),
    _VSO_R_ONE_MAT   VARCHAR(1),
    _VSO_R_ONE_SORT  VARCHAR(1),
    _VSO_R_ULD_SIDE  DECIMAL(1),
    _VSO_R_LOAD_PREF DECIMAL(1),
    _VSO_R_DPOINT    VARCHAR(10),
    constraint KNA1_PK primary key (KUNNR, MANDT)
);

create table MARA
(
    MANDT            CHAR(3)     not null,
    MATNR            VARCHAR(18) not null,
    ERSDA            DATE,
    ERNAM            VARCHAR(12),
    LAEDA            DATE,
    AENAM            VARCHAR(12),
    VPSTA            VARCHAR(15),
    PSTAT            VARCHAR(15),
    LVORM            VARCHAR(1),
    MTART            VARCHAR(4),
    MBRSH            VARCHAR(1),
    MATKL            VARCHAR(9),
    BISMT            VARCHAR(18),
    MEINS            CHAR(3),
    BSTME            CHAR(3),
    ZEINR            VARCHAR(22),
    ZEIAR            VARCHAR(3),
    ZEIVR            VARCHAR(2),
    ZEIFO            VARCHAR(4),
    AESZN            VARCHAR(6),
    BLATT            VARCHAR(3),
    BLANZ            DECIMAL(3),
    FERTH            VARCHAR(18),
    FORMT            VARCHAR(4),
    GROES            VARCHAR(32),
    WRKST            VARCHAR(48),
    NORMT            VARCHAR(18),
    LABOR            VARCHAR(3),
    EKWSL            VARCHAR(4),
    BRGEW            DECIMAL(13, 3),
    NTGEW            DECIMAL(13, 3),
    GEWEI            CHAR(3),
    VOLUM            DECIMAL(13, 3),
    VOLEH            CHAR(3),
    BEHVO            VARCHAR(2),
    RAUBE            VARCHAR(2),
    TEMPB            VARCHAR(2),
    DISST            VARCHAR(3),
    TRAGR            VARCHAR(4),
    STOFF            VARCHAR(18),
    SPART            VARCHAR(2),
    KUNNR            VARCHAR(10),
    EANNR            VARCHAR(13),
    WESCH            DECIMAL(13, 3),
    BWVOR            VARCHAR(1),
    BWSCL            VARCHAR(1),
    SAISO            VARCHAR(4),
    ETIAR            VARCHAR(2),
    ETIFO            VARCHAR(2),
    ENTAR            VARCHAR(1),
    EAN11            VARCHAR(18),
    NUMTP            VARCHAR(2),
    LAENG            DECIMAL(13, 3),
    BREIT            DECIMAL(13, 3),
    HOEHE            DECIMAL(13, 3),
    MEABM            CHAR(3),
    PRDHA            VARCHAR(18),
    AEKLK            VARCHAR(1),
    CADKZ            VARCHAR(1),
    QMPUR            VARCHAR(1),
    ERGEW            DECIMAL(13, 3),
    ERGEI            CHAR(3),
    ERVOL            DECIMAL(13, 3),
    ERVOE            CHAR(3),
    GEWTO            DECIMAL(3, 1),
    VOLTO            DECIMAL(3, 1),
    VABME            VARCHAR(1),
    KZREV            VARCHAR(1),
    KZKFG            VARCHAR(1),
    XCHPF            VARCHAR(1),
    VHART            VARCHAR(4),
    FUELG            DECIMAL(3),
    STFAK            DECIMAL,
    MAGRV            VARCHAR(4),
    BEGRU            VARCHAR(4),
    DATAB            DATE,
    LIQDT            DATE,
    SAISJ            VARCHAR(4),
    PLGTP            VARCHAR(2),
    MLGUT            VARCHAR(1),
    EXTWG            VARCHAR(18),
    SATNR            VARCHAR(18),
    ATTYP            VARCHAR(2),
    KZKUP            VARCHAR(1),
    KZNFM            VARCHAR(1),
    PMATA            VARCHAR(18),
    MSTAE            VARCHAR(2),
    MSTAV            VARCHAR(2),
    MSTDE            DATE,
    MSTDV            DATE,
    TAKLV            VARCHAR(1),
    RBNRM            VARCHAR(9),
    MHDRZ            DECIMAL(4),
    MHDHB            DECIMAL(4),
    MHDLP            DECIMAL(3),
    INHME            CHAR(3),
    INHAL            DECIMAL(13, 3),
    VPREH            DECIMAL(5),
    ETIAG            VARCHAR(18),
    INHBR            DECIMAL(13, 3),
    CMETH            VARCHAR(1),
    CUOBF            DECIMAL(18),
    KZUMW            VARCHAR(1),
    KOSCH            VARCHAR(18),
    SPROF            VARCHAR(1),
    NRFHG            VARCHAR(1),
    MFRPN            VARCHAR(40),
    MFRNR            VARCHAR(10),
    BMATN            VARCHAR(18),
    MPROF            VARCHAR(4),
    KZWSM            VARCHAR(1),
    SAITY            VARCHAR(2),
    PROFL            VARCHAR(3),
    IHIVI            VARCHAR(1),
    ILOOS            VARCHAR(1),
    SERLV            VARCHAR(1),
    KZGVH            VARCHAR(1),
    XGCHP            VARCHAR(1),
    KZEFF            VARCHAR(1),
    COMPL            DECIMAL(2),
    IPRKZ            VARCHAR(1),
    RDMHD            VARCHAR(1),
    PRZUS            VARCHAR(1),
    MTPOS_MARA       VARCHAR(4),
    BFLME            VARCHAR(1),
    MATFI            VARCHAR(1),
    CMREL            VARCHAR(1),
    BBTYP            VARCHAR(1),
    SLED_BBD         VARCHAR(1),
    GTIN_VARIANT     VARCHAR(2),
    GENNR            VARCHAR(18),
    RMATP            VARCHAR(18),
    GDS_RELEVANT     VARCHAR(1),
    _DSD_VC_GROUP    VARCHAR(6),
    _VSO_R_TILT_IND  VARCHAR(1),
    _VSO_R_STACK_IND VARCHAR(1),
    _VSO_R_BOT_IND   VARCHAR(1),
    _VSO_R_TOP_IND   VARCHAR(1),
    _VSO_R_STACK_NO  DECIMAL(3),
    _VSO_R_PAL_IND   VARCHAR(1),
    _VSO_R_PAL_OVR_D DECIMAL(13, 3),
    _VSO_R_PAL_OVR_W DECIMAL(13, 3),
    _VSO_R_PAL_B_HT  DECIMAL(13, 3),
    _VSO_R_PAL_MIN_H DECIMAL(13, 3),
    _VSO_R_TOL_B_HT  DECIMAL(13, 3),
    _VSO_R_NO_P_GVH  DECIMAL(2),
    _VSO_R_QUAN_UNIT CHAR(3),
    _VSO_R_KZGVH_IND VARCHAR(1),
    FASHGRD          VARCHAR(4),
    ZANIMAL_TISSUE   VARCHAR(20),
    ZSTERLIZE_METHOD VARCHAR(20),
    WEORA            VARCHAR(1),
    HUTYP_DFLT       VARCHAR(4),
    PILFERABLE       VARCHAR(1),
    WHSTC            VARCHAR(2),
    WHMATGR          VARCHAR(4),
    HNDLCODE         VARCHAR(4),
    HAZMAT           VARCHAR(1),
    HUTYP            VARCHAR(4),
    TARE_VAR         VARCHAR(1),
    MAXC             DECIMAL(15, 3),
    MAXC_TOL         DECIMAL(3, 1),
    MAXL             DECIMAL(15, 3),
    MAXB             DECIMAL(15, 3),
    MAXH             DECIMAL(15, 3),
    MAXDIM_UOM       CHAR(3),
    HERKL            VARCHAR(3),
    MFRGR            VARCHAR(8),
    QQTIME           DECIMAL(3),
    QQTIMEUOM        CHAR(3),
    QGRP             VARCHAR(4),
    SERIAL           VARCHAR(4),
    PS_SMARTFORM     VARCHAR(30),
    LOGUNIT          CHAR(3),
    CWQREL           VARCHAR(1),
    CWQPROC          VARCHAR(2),
    CWQTOLGR         VARCHAR(9),
    ADPROF           VARCHAR(3),
    _BEV1_LULEINH    DECIMAL(8),
    _BEV1_LULDEGRP   VARCHAR(3),
    _BEV1_NESTRUCCAT VARCHAR(1),
    _DSD_SL_TOLTYP   VARCHAR(4),
    _DSD_SV_CNT_GRP  VARCHAR(10),
    PACKCODE         VARCHAR(10),
    DG_PACK_STATUS   VARCHAR(10),
    MCOND            VARCHAR(1),
    RETDELC          VARCHAR(1),
    LOGLEV_RETO      VARCHAR(1),
    NSNID            VARCHAR(9),
    IMATN            VARCHAR(18),
    PICNUM           VARCHAR(18),
    BSTAT            VARCHAR(2),
    COLOR_ATINN      DECIMAL(10),
    SIZE1_ATINN      DECIMAL(10),
    SIZE2_ATINN      DECIMAL(10),
    COLOR            VARCHAR(18),
    SIZE1            VARCHAR(18),
    SIZE2            VARCHAR(18),
    FREE_CHAR        VARCHAR(18),
    CARE_CODE        VARCHAR(16),
    BRAND_ID         VARCHAR(4),
    FIBER_CODE1      VARCHAR(3),
    FIBER_PART1      DECIMAL(3),
    FIBER_CODE2      VARCHAR(3),
    FIBER_PART2      DECIMAL(3),
    FIBER_CODE3      VARCHAR(3),
    FIBER_PART3      DECIMAL(3),
    FIBER_CODE4      VARCHAR(3),
    FIBER_PART4      DECIMAL(3),
    FIBER_CODE5      VARCHAR(3),
    FIBER_PART5      DECIMAL(3),
    constraint MARA_PK primary key (MATNR, MANDT)
)
;


create table MAKT
(
    MANDT CHAR(3)     not null,
    MATNR VARCHAR(18) not null,
    SPRAS CHAR(1)     not null,
    MAKTX VARCHAR(40),
    MAKTG VARCHAR(40),
    constraint MAKT_PK primary key (MATNR, SPRAS, MANDT)
)
;

create table MCHA
(
    MANDT      CHAR(3)     not null,
    MATNR      VARCHAR(18) not null,
    WERKS      VARCHAR(4)  not null,
    CHARG      VARCHAR(10) not null,
    LVORM      VARCHAR(1),
    ERSDA      DATE,
    ERNAM      VARCHAR(12),
    AENAM      VARCHAR(12),
    LAEDA      DATE,
    VERAB      DATE,
    VFDAT      DATE,
    ZUSCH      VARCHAR(1),
    ZUSTD      VARCHAR(1),
    ZAEDT      DATE,
    LIFNR      VARCHAR(10),
    LICHA      VARCHAR(15),
    VLCHA      VARCHAR(10),
    VLWRK      VARCHAR(4),
    VLMAT      VARCHAR(18),
    BWTAR      VARCHAR(10),
    CHAME      CHAR(3),
    LWEDT      DATE,
    FVDT1      DATE,
    FVDT2      DATE,
    FVDT3      DATE,
    FVDT4      DATE,
    FVDT5      DATE,
    FVDT6      DATE,
    HERKL      VARCHAR(3),
    HERKR      VARCHAR(3),
    MTVER      VARCHAR(4),
    QNDAT      DATE,
    HSDAT      DATE,
    CUOBJ_BM   DECIMAL(18),
    DEACT_BM   VARCHAR(1),
    BATCH_TYPE VARCHAR(1),
    constraint MCHA_PK primary key (MATNR, WERKS, CHARG, MANDT)
)
;


create table T001W
(
    MANDT      CHAR(3)    not null,
    WERKS      VARCHAR(4) not null,
    NAME1      VARCHAR(30),
    BWKEY      VARCHAR(4),
    KUNNR      VARCHAR(10),
    LIFNR      VARCHAR(10),
    FABKL      VARCHAR(2),
    NAME2      VARCHAR(30),
    STRAS      VARCHAR(30),
    PFACH      VARCHAR(10),
    PSTLZ      VARCHAR(10),
    ORT01      VARCHAR(25),
    EKORG      VARCHAR(4),
    VKORG      VARCHAR(4),
    CHAZV      VARCHAR(1),
    KKOWK      VARCHAR(1),
    KORDB      VARCHAR(1),
    BEDPL      VARCHAR(1),
    LAND1      VARCHAR(3),
    REGIO      VARCHAR(3),
    COUNC      VARCHAR(3),
    CITYC      VARCHAR(4),
    ADRNR      VARCHAR(10),
    IWERK      VARCHAR(4),
    TXJCD      VARCHAR(15),
    VTWEG      VARCHAR(2),
    SPART      VARCHAR(2),
    SPRAS      CHAR(1),
    WKSOP      VARCHAR(1),
    AWSLS      VARCHAR(6),
    CHAZV_OLD  VARCHAR(1),
    VLFKZ      VARCHAR(1),
    BZIRK      VARCHAR(6),
    ZONE1      VARCHAR(10),
    TAXIW      VARCHAR(1),
    BZQHL      VARCHAR(1),
    LET01      DECIMAL(3),
    LET02      DECIMAL(3),
    LET03      DECIMAL(3),
    TXNAM_MA1  VARCHAR(16),
    TXNAM_MA2  VARCHAR(16),
    TXNAM_MA3  VARCHAR(16),
    BETOL      DECIMAL(3),
    J_1BBRANCH VARCHAR(4),
    VTBFI      VARCHAR(2),
    FPRFW      VARCHAR(3),
    ACHVM      VARCHAR(1),
    DVSART     VARCHAR(1),
    NODETYPE   VARCHAR(3),
    NSCHEMA    VARCHAR(4),
    PKOSA      VARCHAR(1),
    MISCH      VARCHAR(1),
    MGVUPD     VARCHAR(1),
    VSTEL      VARCHAR(4),
    MGVLAUPD   VARCHAR(1),
    SOURCING   VARCHAR(1),
    MGVLAREVAL VARCHAR(1),
    OILIVAL    VARCHAR(1),
    OIHVTYPE   VARCHAR(1),
    OIHCREDIPI VARCHAR(1),
    STORETYPE  VARCHAR(1),
    DEP_STORE  VARCHAR(4),
    constraint T001W_PK primary key (WERKS, MANDT)
)
;

create table MSKU
(
    MANDT CHAR(3)     not null,
    MATNR VARCHAR(18) not null,
    WERKS VARCHAR(4)  not null,
    CHARG VARCHAR(10) not null,
    SOBKZ VARCHAR(1)  not null,
    KUNNR VARCHAR(10) not null,
    LFGJA DECIMAL(4),
    LFMON DECIMAL(2),
    KUSPR VARCHAR(1),
    KULAB DECIMAL(13, 3),
    KUINS DECIMAL(13, 3),
    KUVLA DECIMAL(13, 3),
    KUVIN DECIMAL(13, 3),
    KUILL VARCHAR(3),
    KUILQ VARCHAR(3),
    KUVLL VARCHAR(3),
    KUVLQ VARCHAR(3),
    KUFLL VARCHAR(3),
    KUFLQ VARCHAR(3),
    KUDLL DATE,
    KUEIN DECIMAL(13, 3),
    KUVEI DECIMAL(13, 3),
    ERSDA DATE,
    KUJIN DECIMAL(4),
    KURUE VARCHAR(1),
    KUUML DECIMAL(13, 3),
    constraint MSKU_PK primary key (MATNR, WERKS, CHARG, SOBKZ, KUNNR, MANDT)
)
;

create table TSPAT
(
    MANDT CHAR(3)    not null,
    SPRAS CHAR(1)    not null,
    SPART VARCHAR(2) not null,
    VTEXT VARCHAR(20),
    constraint SDS_CP_TSPAT_PK primary key (SPRAS, SPART, MANDT)
)
;

create table CABN
(
    MANDT              CHAR(3)     not null,
    ATINN              DECIMAL(10) not null,
    ADZHL              DECIMAL(4)  not null,
    ATNAM              VARCHAR(30),
    ATEIN              VARCHAR(1),
    ATIDN              VARCHAR(2),
    ATFOR              VARCHAR(4),
    ANZST              DECIMAL,
    ANZDZ              DECIMAL,
    ATVOR              VARCHAR(1),
    ATSCH              VARCHAR(30),
    ATKLE              VARCHAR(1),
    ATKON              VARCHAR(5),
    ATEND              VARCHAR(1),
    ATAEN              VARCHAR(1),
    ATKLA              VARCHAR(10),
    ATERF              VARCHAR(1),
    ATAME              VARCHAR(1),
    ATWME              VARCHAR(1),
    MSEHI              CHAR(3),
    ATDIM              DECIMAL,
    ATGLO              VARCHAR(1),
    ATGLA              VARCHAR(1),
    ATINT              VARCHAR(1),
    ATUNS              VARCHAR(1),
    ATSON              VARCHAR(1),
    ATTAB              VARCHAR(30),
    ATFEL              VARCHAR(30),
    ATTEI              VARCHAR(30),
    ATPRT              VARCHAR(30),
    ATPRR              VARCHAR(40),
    ATPRF              VARCHAR(30),
    ATWRD              VARCHAR(1),
    ATFOD              VARCHAR(1),
    ATHIE              VARCHAR(1),
    ATDEX              DECIMAL(1),
    ATFGA              VARCHAR(1),
    ATVSC              VARCHAR(1),
    ANAME              VARCHAR(12),
    ADATU              DATE,
    VNAME              VARCHAR(12),
    VDATU              DATE,
    ATXAC              VARCHAR(1),
    ATYAC              VARCHAR(1),
    ATMST              VARCHAR(1),
    ATWSO              VARCHAR(1),
    ATBSO              VARCHAR(1),
    DATUV              DATE,
    TECHV              VARCHAR(12),
    AENNR              VARCHAR(12),
    LKENZ              VARCHAR(1),
    ATWRI              VARCHAR(1),
    DOKAR              VARCHAR(3),
    DOKNR              VARCHAR(25),
    DOKVR              VARCHAR(2),
    DOKTL              VARCHAR(3),
    KNOBJ              DECIMAL(18),
    ATINP              VARCHAR(1),
    ATVIE              VARCHAR(1),
    WERKS              VARCHAR(4),
    KATALOGART         VARCHAR(1),
    AUSWAHLMGE         VARCHAR(8),
    ATHKA              VARCHAR(1),
    ATHKO              VARCHAR(1),
    CLINT              DECIMAL(10),
    ATTOL              VARCHAR(1),
    ATZUS              VARCHAR(1),
    ATVPL              VARCHAR(1),
    ATAUTH             VARCHAR(3),
    COUNTRYGRP         VARCHAR(1),
    ARCHIVE_FLAG$      CHAR(1),
    ARCHIVE_TIMESTAMP$ DATE,
    constraint SDS_CP_CABN_PK primary key (ATINN, ADZHL, MANDT)
)
;


create table AUSP
(
    MANDT              CHAR(3)     not null,
    OBJEK              VARCHAR(50) not null,
    ATINN              DECIMAL(10) not null,
    KLART              VARCHAR(3)  not null,
    ATZHL              DECIMAL(3)  not null,
    MAFID              VARCHAR(1)  not null,
    ADZHL              DECIMAL(4)  not null,
    ATWRT              VARCHAR(30),
    ATFLV              FLOAT,
    ATAWE              CHAR(3),
    ATFLB              FLOAT,
    ATAW1              CHAR(3),
    ATCOD              VARCHAR(1),
    ATTLV              FLOAT,
    ATTLB              FLOAT,
    ATPRZ              VARCHAR(1),
    ATINC              FLOAT,
    ATAUT              VARCHAR(1),
    AENNR              VARCHAR(12),
    DATUV              DATE,
    LKENZ              VARCHAR(1),
    ATIMB              DECIMAL(10),
    ATZIS              DECIMAL(3),
    ATSRT              DECIMAL(4),
    ATVGLART           VARCHAR(1),
    ARCHIVE_FLAG$      CHAR(1),
    ARCHIVE_TIMESTAMP$ TIME,
    UPDATE_TS          TIMESTAMP default NOW(),
    constraint SDS_CP_AUSP_PK primary key (OBJEK, ATINN, ATZHL, MAFID, KLART, ADZHL, MANDT)
)
;

create table T006
(
    MANDT      CHAR(3) not null,
    MSEHI      CHAR(3) not null,
    ISOCODE    VARCHAR(3),
    KZEX3      VARCHAR(1),
    KZEX6      VARCHAR(1),
    ANDEC      DECIMAL,
    KZKEH      VARCHAR(1),
    KZWOB      VARCHAR(1),
    KZ1EH      VARCHAR(1),
    KZ2EH      VARCHAR(1),
    DIMID      VARCHAR(6),
    ZAEHL      DECIMAL,
    NENNR      DECIMAL,
    EXP10      DECIMAL,
    ADDKO      DECIMAL(9, 6),
    EXPON      DECIMAL,
    DECAN      DECIMAL,
    _PRIMARY_  VARCHAR(1), # PRIMARY is a reserved word, needs to be quoted -- will see if this works with CDC
    TEMP_VALUE FLOAT,
    TEMP_UNIT  CHAR(3),
    FAMUNIT    VARCHAR(1),
    PRESS_VAL  FLOAT,
    PRESS_UNIT CHAR(3),
    constraint SDS_CP_T006_PK primary key (MSEHI, MANDT)
)
;

create table MARM
(
    MANDT        CHAR(3)     not null,
    MATNR        VARCHAR(18) not null,
    MEINH        CHAR(3)     not null,
    UMREZ        DECIMAL(5),
    UMREN        DECIMAL(5),
    EANNR        VARCHAR(13),
    EAN11        VARCHAR(18),
    NUMTP        VARCHAR(2),
    LAENG        DECIMAL(13, 3),
    BREIT        DECIMAL(13, 3),
    HOEHE        DECIMAL(13, 3),
    MEABM        CHAR(3),
    VOLUM        DECIMAL(13, 3),
    VOLEH        CHAR(3),
    BRGEW        DECIMAL(13, 3),
    GEWEI        CHAR(3),
    MESUB        CHAR(3),
    ATINN        DECIMAL(10),
    MESRT        DECIMAL(2),
    XFHDW        VARCHAR(1),
    XBEWW        VARCHAR(1),
    KZWSO        VARCHAR(1),
    MSEHI        CHAR(3),
    BFLME_MARM   VARCHAR(1),
    GTIN_VARIANT VARCHAR(2),
    NEST_FTR     DECIMAL(3),
    MAX_STACK    DECIMAL,
    CAPAUSE      DECIMAL(15, 3),
    TY2TQ        VARCHAR(1),
    constraint SDS_CP_MARM_PK primary key (MATNR, MEINH, MANDT)
)
;


create table MVKE
(
    MANDT           CHAR(3)     not null,
    MATNR           VARCHAR(18) not null,
    VKORG           VARCHAR(4)  not null,
    VTWEG           VARCHAR(2)  not null,
    LVORM           VARCHAR(1),
    VERSG           VARCHAR(1),
    BONUS           VARCHAR(2),
    PROVG           VARCHAR(2),
    SKTOF           VARCHAR(1),
    VMSTA           VARCHAR(2),
    VMSTD           DATE,
    AUMNG           DECIMAL(13, 3),
    LFMNG           DECIMAL(13, 3),
    EFMNG           DECIMAL(13, 3),
    SCMNG           DECIMAL(13, 3),
    SCHME           CHAR(3),
    VRKME           CHAR(3),
    MTPOS           VARCHAR(4),
    DWERK           VARCHAR(4),
    PRODH           VARCHAR(18),
    PMATN           VARCHAR(18),
    KONDM           VARCHAR(2),
    KTGRM           VARCHAR(2),
    MVGR1           VARCHAR(3),
    MVGR2           VARCHAR(3),
    MVGR3           VARCHAR(3),
    MVGR4           VARCHAR(3),
    MVGR5           VARCHAR(3),
    SSTUF           VARCHAR(2),
    PFLKS           VARCHAR(1),
    LSTFL           VARCHAR(2),
    LSTVZ           VARCHAR(2),
    LSTAK           VARCHAR(1),
    LDVFL           DATE,
    LDBFL           DATE,
    LDVZL           DATE,
    LDBZL           DATE,
    VDVFL           DATE,
    VDBFL           DATE,
    VDVZL           DATE,
    VDBZL           DATE,
    PRAT1           VARCHAR(1),
    PRAT2           VARCHAR(1),
    PRAT3           VARCHAR(1),
    PRAT4           VARCHAR(1),
    PRAT5           VARCHAR(1),
    PRAT6           VARCHAR(1),
    PRAT7           VARCHAR(1),
    PRAT8           VARCHAR(1),
    PRAT9           VARCHAR(1),
    PRATA           VARCHAR(1),
    RDPRF           VARCHAR(4),
    MEGRU           VARCHAR(4),
    LFMAX           DECIMAL(13, 3),
    RJART           VARCHAR(1),
    PBIND           VARCHAR(1),
    VAVME           VARCHAR(1),
    MATKC           VARCHAR(1),
    PVMSO           DECIMAL(8),
    _BEV1_EMLGRP    VARCHAR(4),
    _BEV1_EMDRCKSPL DECIMAL(1),
    _BEV1_RPBEZME   CHAR(3),
    _BEV1_RPSNS     VARCHAR(1),
    _BEV1_RPSFA     VARCHAR(1),
    _BEV1_RPSKI     VARCHAR(1),
    _BEV1_RPSCO     VARCHAR(1),
    _BEV1_RPSSO     VARCHAR(1),
    PLGTP           VARCHAR(2),
    constraint SDS_CP_MVKE_PK primary key (MATNR, VKORG, VTWEG, MANDT)
)
;

create table T178T
(
    MANDT CHAR(3)    not null,
    SPRAS CHAR(1)    not null,
    KONDM VARCHAR(2) not null,
    VTEXT VARCHAR(20),
    constraint SDS_CP_T178T_PK primary key (SPRAS, KONDM, MANDT)
)
;

create table ZIPCODE
(
    ZIPCODE   VARCHAR(5) not null,
    CITY      VARCHAR(10),
    STATE     CHAR(2),
    LATITUDE  DECIMAL(10, 6),
    LONGITUDE DECIMAL(10, 6),
    TIMEZONE  INTEGER(2),
    DST       CHAR(1),
    GEO_POINT VARCHAR(24),
    constraint ZIPCODE_PK primary key (ZIPCODE)
)
;

create table if not exists ZIPCODE2
(
    ZIPCODE    VARCHAR(5) not null,
    STATE_FIPS INTEGER(2),
    STATE      CHAR(12),
    STATE_ABBR CHAR(2),
    COUNTY     VARCHAR(15),
    CITY       VARCHAR(15),
    COUNTY_FIPS INTEGER(5),

    constraint ZIPCODE2_PK primary key (ZIPCODE)
)
;
