version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./zookeeper-data:/var/lib/zookeeper
      - ./zookeeper-conf:/etc/zookeeper/conf

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,SASL_SSL://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,SASL_SSL://kafka:9093
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/ssl/kafka.keystore
      KAFKA_SSL_KEYSTORE_PASSWORD: confluent
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/ssl/kafka.truststore
      KAFKA_SSL_TRUSTSTORE_PASSWORD: confluent
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512
      KAFKA_SASL_MECHANISM: SCRAM-SHA-512
      KAFKA_SASL_USERNAME: my-user
      KAFKA_SASL_PASSWORD: my-password
    volumes:
      - ./kafka-data:/var/lib/kafka
      - ./kafka-conf:/etc/kafka/conf

volumes:
  zookeeper-data:
  zookeeper-conf:
  kafka-data:
  kafka-conf:

networks:
  kafka-cluster-network:
