---
version: '3.7'

networks:
  default:
    external:
      name: kafka-local

services:

  mysql:
    image: mysql:8.0.21
    #image: mysql:5.7
    hostname: mysql
    container_name: kl_mysql
    ports:
      - "3306:3306"
    volumes:
#      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./cnf/local.cnf:/etc/mysql/conf.d/local.cnf
      - ./init.d:/docker-entrypoint-initdb.d
      - ./data:/data
    environment:
      MYSQL_ROOT_PASSWORD: debezium 
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw

#  sqlpad:
#    image: sqlpad/sqlpad:4.0.0
#    hostname: sqlpad
#    container_name: kl_sqlpad
#    depends_on:
#      - mysql
#    ports:
#      - '3001:3000'
#    environment:
#      SQLPAD_CONFIG: /etc/sqlpad/config.json
#    volumes:
#      - ./sqlpad.json:/etc/sqlpad/config.json
