lowercaseOutputName: true
rules:
#- pattern: kafka.(.*)
- pattern: java.lang<type=(.*)>
- pattern: kafka.streams<type=stream-thread-metrics, thread-id=(.+)><>(.+):.+
  name: kafka_streams_stream_thread_metrics_$2
  labels:
    thread_id: "$1"
- pattern: kafka.producer<type=producer-metrics, client-id=(.+)><>(.+):.+
  name: kafka_producer_producer_metrics_$2
  labels:
    client_id: "$1"
- pattern: kafka.consumer<type=consumer-metrics, client-id=(.+)><>(.+):.+
  name: kafka_consumer_consumer_metrics_$2
  labels:
    client_id: "$1"

