alter session set current_schema=KAFKA_MAIN;

CREATE TABLE "ENTPR_SOURCE_OB"
(
SOURCE_KEY_ID             VARCHAR2(120 CHAR) NOT NULL,
LGCY_SOURCE_KEY_ID                VARCHAR2(120 CHAR) ,
SOURCE                    VARCHAR2(25 CHAR)  NOT NULL,
SOURCE_SHORT_NM                   VARCHAR2(50 CHAR)  ,
SOURCE_LONG_NM                    VARCHAR2(100 CHAR) ,
SOURCE_DESC                       VARCHAR2(100 CHAR) ,
SMART_KEY_PREFIX_VAL              VARCHAR2(25 CHAR)  ,
EDS_INTERACTION_METH_VAL          VARCHAR2(25 CHAR)  ,
TRANS_SEQ_NUM             NUMBER(13)    NOT NULL      ,
CREATE_SOURCE                     VARCHAR2(25 CHAR)  ,
SOURCE_CREATE_USER                VARCHAR2(25 CHAR)  ,
SOURCE_CREATE_TS                  TIMESTAMP(6)       ,
UPD_SOURCE                        VARCHAR2(25 CHAR)  ,
SOURCE_UPD_USER                   VARCHAR2(25 CHAR)  ,
SOURCE_UPD_TS                     TIMESTAMP(6)       ,
UPD_TS                    TIMESTAMP(6) NOT NULL,
PRIMARY KEY ("SOURCE_KEY_ID")
);



CREATE TABLE "ENTPR_REF_VAL_OB"
(
SOURCE_KEY_ID       VARCHAR2(120 CHAR) NOT NULL ,
REF_VAL             VARCHAR2(50 CHAR)  NOT NULL ,
SOURCE_ID           VARCHAR2(255 CHAR) NOT NULL ,
REF_VAL_SHORT_NM            VARCHAR2(50 CHAR)   ,
REF_VAL_MEDIUM_NM           VARCHAR2(50 CHAR)   ,
REF_VAL_LONG_NM             VARCHAR2(50 CHAR)   ,
REF_VAL_DESC                VARCHAR2(1000 CHAR) ,
REF_VAL_SET_IND     VARCHAR2(10 CHAR)   NOT NULL,
TRANS_SEQ_NUM       NUMBER(13)        NOT NULL  ,
CREATE_SOURCE               VARCHAR2(25 CHAR)   ,
SOURCE_CREATE_USER          VARCHAR2(25 CHAR)   ,
SOURCE_CREATE_TS            TIMESTAMP(6)        ,
UPD_SOURCE                  VARCHAR2(25 CHAR)   ,
SOURCE_UPD_USER             VARCHAR2(25 CHAR)   ,
SOURCE_UPD_TS               TIMESTAMP(6)        ,
UPD_TS              TIMESTAMP(6) NOT NULL,
    PRIMARY KEY ("SOURCE_KEY_ID", "REF_VAL")
);



CREATE TABLE "ENTPR_REF_VAL_RLSHP_OB"
(
SOURCE_KEY_ID         VARCHAR2(120 CHAR) NOT NULL,
REF_VAL               VARCHAR2(50 CHAR) NOT NULL ,
REL_REF_VAL           VARCHAR2(50 CHAR)  NOT NULL,
SOURCE_ID             VARCHAR2(255 CHAR) NOT NULL,
REF_VAL_RLSHP_TYP_ID  VARCHAR2(10 CHAR)  NOT NULL,
HRCHY_LVL_NUM                 NUMBER             ,
TRANS_SEQ_NUM         NUMBER(13)         NOT NULL,
CREATE_SOURCE                 VARCHAR2(25 CHAR)  ,
SOURCE_CREATE_USER            VARCHAR2(25 CHAR)  ,
SOURCE_CREATE_TS              TIMESTAMP(6)       ,
UPD_SOURCE                    VARCHAR2(25 CHAR)  ,
SOURCE_UPD_USER               VARCHAR2(25 CHAR)  ,
SOURCE_UPD_TS                 TIMESTAMP(6)       ,
UPD_TS                TIMESTAMP(6)  NOT NULL,
    PRIMARY KEY ("SOURCE_KEY_ID", "REF_VAL", "REL_REF_VAL")
);


CREATE TABLE "ENTPR_REF_VAL_RLSHP_TYP_OB"
(
REF_VAL_RLSHP_TYP_ID VARCHAR2(10 CHAR) NOT NULL ,
REF_VAL_RLSHP_TYP_NM  VARCHAR2(50 CHAR) NOT NULL,
TRANS_SEQ_NUM         NUMBER(13)     NOT NULL   ,
CREATE_SOURCE                 VARCHAR2(25 CHAR) ,
SOURCE_CREATE_USER            VARCHAR2(25 CHAR) ,
SOURCE_CREATE_TS              TIMESTAMP(6)      ,
UPD_SOURCE                    VARCHAR2(25 CHAR) ,
SOURCE_UPD_USER               VARCHAR2(25 CHAR) ,
SOURCE_UPD_TS                 TIMESTAMP(6)      ,
UPD_TS               TIMESTAMP(6) NOT NULL ,
    PRIMARY KEY ("REF_VAL_RLSHP_TYP_ID")
);

