alter session set current_schema=RPL_MAIN;

CREATE TABLE RPL_MAIN.RPL_HOLD_PATIENT
(
  PATIENT_NO    VARCHAR2(25 BYTE),
  PATIENT_NAME  VARCHAR2(60 BYTE),
  ADDRESS1      VARCHAR2(200 BYTE),
  ADDRESS2      VARCHAR2(100 BYTE),
  PHONE         VARCHAR2(26 BYTE),
  CITY          VARCHAR2(60 BYTE),
  STATE_CODE    VARCHAR2(15 BYTE),
  POSTAL_CODE   VARCHAR2(30 BYTE),
  COUNTRY_ID    VARCHAR2(30 BYTE),
  LOAD_DATE     DATE,
  SSN           VARCHAR2(25 BYTE),
  PATIENT_ID    VARCHAR2(25 BYTE)
);

CREATE INDEX RPL_MAIN.NAME_INDEX ON RPL_MAIN.RPL_HOLD_PATIENT(PATIENT_NAME);
CREATE INDEX RPL_MAIN.PHONE_INDEX ON RPL_MAIN.RPL_HOLD_PATIENT(PHONE);
CREATE UNIQUE INDEX RPL_MAIN.PK_PATIENT_NO ON RPL_MAIN.RPL_HOLD_PATIENT(PATIENT_NO);
CREATE INDEX RPL_MAIN.POSTAL_CODE_INDEX ON RPL_MAIN.RPL_HOLD_PATIENT(POSTAL_CODE);
CREATE INDEX RPL_MAIN.SSN_INDEX ON RPL_MAIN.RPL_HOLD_PATIENT(SSN);

ALTER TABLE RPL_MAIN.RPL_HOLD_PATIENT ADD (
  CONSTRAINT PK_PATIENT_NO
  PRIMARY KEY
  (PATIENT_NO)
  USING INDEX RPL_MAIN.PK_PATIENT_NO
  ENABLE VALIDATE);

CREATE TABLE RPL_MAIN.RPL_HOLD_MATERIAL
(
  LOT_SERIAL_NUM       VARCHAR2(30 CHAR),
  UPN_ID               VARCHAR2(30 CHAR),
  BATCH_FID            VARCHAR2(30 CHAR),
  SOURCE               VARCHAR2(5 CHAR),
  MATERIAL_DESC        VARCHAR2(255 CHAR),
  MATERIAL_TYPE        VARCHAR2(30 CHAR),
  LOAD_DATE            DATE                     DEFAULT SYSDATE,
  BATCH_CREATION_DATE  DATE
);

CREATE INDEX RPL_MAIN.LOT_SERIAL_INDEX ON RPL_MAIN.RPL_HOLD_MATERIAL(LOT_SERIAL_NUM);
CREATE UNIQUE INDEX RPL_MAIN.PK_LOT_SERIAL ON RPL_MAIN.RPL_HOLD_MATERIAL(LOT_SERIAL_NUM, UPN_ID);

ALTER TABLE RPL_MAIN.RPL_HOLD_MATERIAL ADD (
  CONSTRAINT PK_LOT_SERIAL
  PRIMARY KEY
  (LOT_SERIAL_NUM, UPN_ID)
  USING INDEX RPL_MAIN.PK_LOT_SERIAL
  ENABLE VALIDATE);

CREATE TABLE RPL_MAIN.RPL_HOLD_HCP
(
  HCP_ID           VARCHAR2(25 BYTE),
  FIRST_NAME       VARCHAR2(60 BYTE),
  LAST_NAME        VARCHAR2(60 BYTE),
  NAME_SALUTATION  VARCHAR2(20 BYTE),
  NAME_SUFFIX      VARCHAR2(20 BYTE),
  NAME_SORT        VARCHAR2(60 BYTE),
  ADDRESS1         VARCHAR2(200 BYTE),
  ADDRESS2         VARCHAR2(100 BYTE),
  ADDRESS3         VARCHAR2(100 BYTE),
  ADDRESS4         VARCHAR2(100 BYTE),
  CITY             VARCHAR2(60 BYTE),
  STATE_CODE       VARCHAR2(15 BYTE),
  POSTAL_CODE      VARCHAR2(30 BYTE),
  COUNTRY_ID       VARCHAR2(30 BYTE),
  PHONE            VARCHAR2(26 BYTE),
  LOAD_DATE        DATE,
  CONTACT_ID       VARCHAR2(25 BYTE)
);

CREATE INDEX RPL_MAIN.HCP_ID_INDEX ON RPL_MAIN.RPL_HOLD_HCP(HCP_ID);
CREATE INDEX RPL_MAIN.NAME_SORT_INDEX ON RPL_MAIN.RPL_HOLD_HCP(NAME_SORT);
CREATE INDEX RPL_MAIN.PHONE_HCP_INDEX ON RPL_MAIN.RPL_HOLD_HCP(PHONE);
CREATE UNIQUE INDEX RPL_MAIN.PK_CONTACT_ID ON RPL_MAIN.RPL_HOLD_HCP(CONTACT_ID);
CREATE INDEX RPL_MAIN.POSTAL_CODE_HCP_INDEX ON RPL_MAIN.RPL_HOLD_HCP(POSTAL_CODE);

ALTER TABLE RPL_MAIN.RPL_HOLD_HCP ADD (
  CONSTRAINT PK_HCP_ID
  PRIMARY KEY
  (CONTACT_ID)
  USING INDEX RPL_MAIN.PK_HCP_ID
  ENABLE VALIDATE);


CREATE TABLE RPL_MAIN.RPL_HOLD_DEVICE_IMPLANT
(
  DEVICE_ID                   VARCHAR2(80 CHAR),
  SOURCE                      VARCHAR2(5 CHAR),
  IMPLANT_ACTIVE_FLAG         CHAR(1 CHAR)      DEFAULT 'N',
  IMPLANT_STATUS_DATE         DATE,
  IMPLANT_STATUS_CODE         VARCHAR2(10 CHAR),
  PATIENT_ID                  VARCHAR2(25 CHAR),
  PATIENT_AGE                 NUMBER(3),
  IMPLANT_DATE                DATE,
  EXPLANT_DATE                DATE,
  REPLACED_DATE               DATE,
  IMPLANT_ADDR_SOURCE         VARCHAR2(5 CHAR),
  IMPLANT_ADDR_ID             VARCHAR2(25 CHAR),
  ACCT_ID                     NUMBER(10),
  FOLLOWUP_ADDR_SOURCE        VARCHAR2(5 CHAR),
  FOLLOWUP_ADDR_ID            VARCHAR2(25 CHAR),
  PREVIOUS_DEVICE_ID          VARCHAR2(80 CHAR),
  PREVIOUS_MFG_CODE           VARCHAR2(10 CHAR),
  PREVIOUS_MODEL_NO           VARCHAR2(25 CHAR),
  PREVIOUS_LOT_SERIAL_NUM     VARCHAR2(30 CHAR),
  SECOND_PREV_DEVICE_ID       VARCHAR2(80 CHAR),
  SECOND_PREV_MFG_CODE        VARCHAR2(10 CHAR),
  SECOND_PREV_MODEL_NO        VARCHAR2(25 CHAR),
  SECOND_PREV_LOT_SERIAL_NUM  VARCHAR2(30 CHAR),
  REPLACED_BY_DEVICE_ID       VARCHAR2(80 CHAR),
  REPLACED_BY_MFG_CODE        VARCHAR2(10 CHAR),
  REPLACED_BY_MODEL_NO        VARCHAR2(25 CHAR),
  REPLACED_BY_LOT_SERIAL_NUM  VARCHAR2(30 CHAR),
  INVOICE_FOUND_CODE          VARCHAR2(10 CHAR),
  UPLOAD_USER_ID              VARCHAR2(25 CHAR),
  UPLOAD_DATE                 DATE,
  REGISTRATION_ORIGIN         VARCHAR2(10 CHAR),
  REGISTRATION_STATUS         VARCHAR2(10 CHAR),
  REPLACEMENT_CODE            VARCHAR2(10 CHAR),
  CREATE_USER_ID              VARCHAR2(25 CHAR),
  CREATE_DATE                 DATE,
  UPDATE_USER_ID              VARCHAR2(25 CHAR),
  UPDATE_DATE                 DATE,
  REUSED_DEVICE_FLAG          VARCHAR2(2 CHAR),
  CHAMBPACED_CODE             VARCHAR2(20 CHAR),
  EXTN_UPLOAD_DATE            DATE,
  EXTN_PAYER_CODE             VARCHAR2(10 CHAR),
  EXTN_IMPLANT_FACILITY_TYPE  VARCHAR2(3 CHAR),
  EXTN_IMPLANT_SITE_CODE      VARCHAR2(10 CHAR),
  EXTN_CODE1                  VARCHAR2(10 CHAR),
  EXTN_CODE2                  VARCHAR2(10 CHAR),
  EXTN_CODE3                  VARCHAR2(10 CHAR),
  EXTN_CREATE_USER_ID         VARCHAR2(25 CHAR),
  EXTN_CHANGE_USER_ID         VARCHAR2(25 CHAR),
  HVD_IMPLANT_POSITION        VARCHAR2(25 CHAR),
  SERVICE_STATUS_CODE         VARCHAR2(25 CHAR),
  SERVICE_STATUS_DATE         DATE,
  SHORT_DESCRIPTION           VARCHAR2(25 CHAR),
  MAIN_DEVICE_CALIBRATION     VARCHAR2(25 CHAR),
  DRUG_CODE                   VARCHAR2(10 CHAR),
  CATHETER_IMPLANT_POSITION   VARCHAR2(25 CHAR),
  LOAD_DATE                   DATE              DEFAULT SYSDATE,
  DART_PATIENT_ID             VARCHAR2(25 BYTE)
);

CREATE INDEX RPL_MAIN.PATIENT_ID_INDEX ON RPL_MAIN.RPL_HOLD_DEVICE_IMPLANT(PATIENT_ID);
CREATE UNIQUE INDEX RPL_MAIN.PK_DEVICE_IMP_ID ON RPL_MAIN.RPL_HOLD_DEVICE_IMPLANT(DEVICE_ID);

ALTER TABLE RPL_MAIN.RPL_HOLD_DEVICE_IMPLANT ADD (
  CONSTRAINT PK_DEVICE_IMP_ID
  PRIMARY KEY
  (DEVICE_ID)
  USING INDEX RPL_MAIN.PK_DEVICE_IMP_ID
  ENABLE VALIDATE);

CREATE TABLE RPL_MAIN.RPL_HOLD_DEVICE
(
  DEVICE_ID                  VARCHAR2(80 CHAR),
  SOURCE                     VARCHAR2(5 CHAR),
  PROD_ID                    VARCHAR2(25 CHAR),
  MFG_CODE                   VARCHAR2(10 CHAR),
  MODEL_NO                   VARCHAR2(25 CHAR),
  LOT_SERIAL_NUM             VARCHAR2(30 CHAR),
  SERIAL_ID                  VARCHAR2(30 CHAR),
  ADDR_ID                    VARCHAR2(25 CHAR),
  QUANTITY                   NUMBER,
  LOCATION_STATUS            VARCHAR2(10 CHAR),
  LOCATION_DATE              DATE,
  TRANSACTION_ID             VARCHAR2(80 CHAR),
  TRANSACTION_LOAD_SOURCE    VARCHAR2(5 CHAR),
  ORDER_ID                   VARCHAR2(40 CHAR),
  ORDER_LOAD_SOURCE          VARCHAR2(5 CHAR),
  INVENTORY_LOCATION_ID      VARCHAR2(25 CHAR),
  INVENTORY_LOCATION_SOURCE  VARCHAR2(5 CHAR),
  CONFIG_CODE                VARCHAR2(80 CHAR),
  BUSINESS_ID                VARCHAR2(25 CHAR),
  ITEM_TYPE                  VARCHAR2(25 CHAR),
  LOAD_DATE                  DATE               DEFAULT SYSDATE
);

CREATE INDEX RPL_MAIN.LOT_SERIAL_NUM_INDEX ON RPL_MAIN.RPL_HOLD_DEVICE(LOT_SERIAL_NUM);
CREATE UNIQUE INDEX RPL_MAIN.PK_DEVICE_ID ON RPL_MAIN.RPL_HOLD_DEVICE(DEVICE_ID, SOURCE);

ALTER TABLE RPL_MAIN.RPL_HOLD_DEVICE ADD (
  CONSTRAINT PK_DEVICE_ID
  PRIMARY KEY
  (DEVICE_ID, SOURCE)
  USING INDEX RPL_MAIN.PK_DEVICE_ID
  ENABLE VALIDATE);

CREATE TABLE RPL_MAIN.RPL_HOLD_ADDRESS_BOOK
(
  ADDR_ID         VARCHAR2(25 BYTE),
  ADDR_NAME       VARCHAR2(60 BYTE),
  NAME2           VARCHAR2(35 BYTE),
  ADDRESS1        VARCHAR2(40 BYTE),
  ADDRESS2        VARCHAR2(40 BYTE),
  ADDRESS3        VARCHAR2(40 BYTE),
  ADDRESS4        VARCHAR2(40 BYTE),
  STATE_CODE      VARCHAR2(10 BYTE),
  POSTAL_CODE     VARCHAR2(12 BYTE),
  SHIP_TO_PARENT  VARCHAR2(25 BYTE),
  CITY            VARCHAR2(40 BYTE),
  COUNTRY_ID      VARCHAR2(25 BYTE),
  PHONE           VARCHAR2(26 BYTE),
  ADDR_TYPE_ID    VARCHAR2(25 BYTE),
  SHORT_NAME      VARCHAR2(40 BYTE),
  LOAD_DATE       DATE,
  US_CUST_TYPE    VARCHAR2(10 BYTE),
  ADDR_GROUP      VARCHAR2(5 BYTE)
);

CREATE UNIQUE INDEX RPL_MAIN.PK_ADDR_ID ON RPL_MAIN.RPL_HOLD_ADDRESS_BOOK(ADDR_ID);
CREATE INDEX RPL_MAIN.POSTALCODE_INDEX ON RPL_MAIN.RPL_HOLD_ADDRESS_BOOK(POSTAL_CODE);
CREATE INDEX RPL_MAIN.SHORT_NAME_INDEX ON RPL_MAIN.RPL_HOLD_ADDRESS_BOOK(SHORT_NAME);

ALTER TABLE RPL_MAIN.RPL_HOLD_ADDRESS_BOOK ADD (
  CONSTRAINT PK_ADDR_ID
  PRIMARY KEY
  (ADDR_ID)
  USING INDEX RPL_MAIN.PK_ADDR_ID
  ENABLE VALIDATE);

