---
version: '3.7'

networks:
  default:
    external:
      name: kafka-local

services:

  connect-1:
    #image: confluentinc/cp-kafka-connect:6.0.1
    build: ./docker
    hostname: connect-1
    container_name: kl_connect-1
    ports:
      - "18083:8083"
    volumes:
      - ./connect-lib:/opt/kafka-connect-lib
      - ./secrets:/etc/kafka/secrets
#      - ./connect-lib:/opt/kafka-connect-lib
#      - ./jars/mysql-connector-java-5.1.48.jar:/usr/share/java/kafka-connect-jdbc/mysql-connector-java-5.1.48.jar
#      - ./jars/kafka-connect-elasticsearch-5.5.0.jar:/usr/share/java/kafka-connect-elasticsearch/kafka-connect-elasticsearch-6.0.1.jar
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker-1:9092,broker-2:9092,broker-3:9092,broker-4:9092'
      CONNECT_REST_PORT: 8083
      CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: 'All'
      CONNECT_GROUP_ID: 'connect-cluster'
      CONNECT_CONFIG_STORAGE_TOPIC: 'connect-cluster-config'
      CONNECT_OFFSET_STORAGE_TOPIC: 'connect-cluster-offsets'
      CONNECT_STATUS_STORAGE_TOPIC: 'connect-cluster-status'
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_CONFIG_PROVIDERS: file
      CONNECT_CONFIG_PROVIDERS_FILE_CLASS: 'org.apache.kafka.common.config.provider.FileConfigProvider'
      CONNECT_KEY_CONVERTER: 'io.confluent.connect.avro.AvroConverter'
      CONNECT_VALUE_CONVERTER: 'io.confluent.connect.avro.AvroConverter'
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_INTERNAL_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_INTERNAL_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_REST_ADVERTISED_HOST_NAME: 'connect-1'
      CONNECT_PLUGIN_PATH: /opt/kafka-connect-lib,/usr/share/java,/usr/share/confluent-hub-components
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_HEAP_OPTS: "-Xmx2G -Xms2G"
  
  connect-2:
    #image: confluentinc/cp-kafka-connect:6.0.1
    build: ./docker
    hostname: connect-2
    container_name: kl_connect-2
    ports:
      - "28083:8083"
    volumes:
      - ./connect-lib:/opt/kafka-connect-lib
      - ./secrets:/etc/kafka/secrets
      #- ./connect-lib/kafka-connect-medtronic-smt-1.0.0:/usr/share/confluent-hub-components/kafka-connect-medtronic-smt
      #- ./connect-lib:/opt/kafka-connect-lib
#      - ./jars/mysql-connector-java-5.1.48.jar:/usr/share/java/kafka-connect-jdbc/mysql-connector-java-5.1.48.jar
#      - ./jars/kafka-connect-elasticsearch-5.5.0.jar:/usr/share/java/kafka-connect-elasticsearch/kafka-connect-elasticsearch-6.0.1.jar
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker-1:9092,broker-2:9092,broker-3:9092,broker-4:9092'
      CONNECT_REST_PORT: 8083
      CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: 'All'
      CONNECT_GROUP_ID: 'connect-cluster'
      CONNECT_CONFIG_STORAGE_TOPIC: 'connect-cluster-config'
      CONNECT_OFFSET_STORAGE_TOPIC: 'connect-cluster-offsets'
      CONNECT_STATUS_STORAGE_TOPIC: 'connect-cluster-status'
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_CONFIG_PROVIDERS: file
      CONNECT_CONFIG_PROVIDERS_FILE_CLASS: 'org.apache.kafka.common.config.provider.FileConfigProvider'
      CONNECT_KEY_CONVERTER: 'io.confluent.connect.avro.AvroConverter'
      CONNECT_VALUE_CONVERTER: 'io.confluent.connect.avro.AvroConverter'
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_INTERNAL_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_INTERNAL_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_REST_ADVERTISED_HOST_NAME: 'connect-2'
      CONNECT_PLUGIN_PATH: /opt/kafka-connect-lib,/usr/share/java,/usr/share/confluent-hub-components
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_HEAP_OPTS: "-Xmx2G -Xms2G"
