{
 "title": "Client - Streams",
 "tags": [
  "Kafka Streams",
  "Kafka Client"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "kafka_streams_stream_thread_metrics_task_created_total"
   },
   {
    "name": "thread",
    "label": "thread",
    "query": "kafka_streams_stream_thread_metrics_task_created_total"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"${job}\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"${job}\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"${job}\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "process rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_process_rate{thread_id=\"${thread}\", job=\"${job}\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "process total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kafka_streams_stream_thread_metrics_process_total{client_id != \"\", job=\"${job}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "commit rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_commit_rate{job=\"${job}\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "commit total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kafka_streams_stream_thread_metrics_commit_total{client_id != \"\", job=\"${job}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "poll rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_rate{job=\"${job}\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "poll total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kafka_streams_stream_thread_metrics_poll_total{client_id != \"\", job=\"${job}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  }
 ]
}