{
 "title": "Client - Consumer",
 "tags": [ "Kafka Client" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "kafka_consumer_consumer_metrics_connection_count"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"${job}\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"${job}\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"${job}\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_request_rate{job=\"${job}\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "request total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kafka_consumer_consumer_metrics_request_total{client_id != \"\", job=\"${job}\"})",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "response rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_response_rate{job=\"${job}\"}",
     "legendFormat": "{{instance}}--{{client_id}}"
    }
   ]
  },
  {
   "title": "response total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kafka_consumer_consumer_metrics_response_total{client_id != \"\", job=\"${job}\"})",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "incoming byte rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_incoming_byte_rate{job=\"${job}\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "incoming byte  total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kafka_consumer_consumer_metrics_incoming_byte_total{client_id != \"\", job=\"${job}\"})",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "outgoing byte rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_outgoing_byte_rate{job=\"${job}\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "outgoing byte total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kafka_consumer_consumer_metrics_outgoing_byte_total{client_id != \"\", job=\"${job}\"})",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  }
 ]
}